In [1]:
for i in range(5):
    for j in range(0,i):
        print("*")

*
*
*
*
*
*
*
*
*
*


In [8]:
for i in range(0,i):
    for j in range(5):
        print("*",end=" ")
    print("\n")

* * * * * 

* * * * * 

* * * * * 

* * * * * 



In [12]:
for i in range(0,4):
    for j in range(0,4):
        if(i+j>=3):
            print("*",end=" ")
        else:
            print(" ",end=" ")
    print()

      * 
    * * 
  * * * 
* * * * 


In [13]:
name=input('enter a name: ')
for i in range(len(name)):
    for j in range(0,i+1):
         print(name[i],end='')
    print()

enter a name: shreyan
s
hh
rrr
eeee
yyyyy
aaaaaa
nnnnnnn


In [14]:
rec={}
n=int(input('enter the no of students:'))
i=1
while i<=n:
    name=input('enter the student name')
    marks=input('enter % marks of student')
    rec[name]=marks
    i+=1
print('name of the student','\t','%of marks')
for x in rec:
    print('\t',x,'\t\t',rec[x])

enter the no of students:1
enter the student nameshreyan
enter % marks of student45
name of the student 	 %of marks
	 shreyan 		 45


In [15]:
d={1:'mite',2:'yfyf'}
d


{1: 'mite', 2: 'yfyf'}

In [17]:

del d

In [18]:
d

NameError: name 'd' is not defined

In [20]:
word=input('enter any word:')
d={}
for x in word:
    d[x]=d.get(x,0)+1
for k,v in d.items():
    print(k,'occurence',v,'times')

enter any word:qqwwwsssdddfffggg rr
q occurence 2 times
w occurence 3 times
s occurence 3 times
d occurence 3 times
f occurence 3 times
g occurence 3 times
  occurence 1 times
r occurence 2 times


In [23]:
word=input('enter any word:')
d={}
vowels={'a','e','i','o','u'}
for x in word:
    if x in vowels:
        d[x]=d.get(x,0)+1
for k,v in d.items():
    print(k,'occurence',v,'times')

enter any word:hello
e occurence 1 times
o occurence 1 times


In [24]:
squares={x:x*x for x in range(1,6)}
print(squares)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}


In [26]:
n=[1,2,3,4,5,5,5]
print(n.count(5))

3


In [27]:
n=[1,2,3,4,5]
n.insert(1,888)
print(n)

[1, 888, 2, 3, 4, 5]


In [28]:
list1=[1,2,3,4]
list2=[4,32,23,1]
list1.extend(list2)
print(list1)

[1, 2, 3, 4, 4, 32, 23, 1]


### remove

In [29]:
list1.pop()

1

In [30]:
print(list1)

[1, 2, 3, 4, 4, 32, 23]


In [31]:
list1.reverse()

In [32]:
print(list1)

[23, 32, 4, 4, 3, 2, 1]


In [34]:
l=['shoba','reevan jenny','prat']
l.sort()
print(l)

['prat', 'reevan jenny', 'shoba']


In [38]:
l=['shoba1','reevan 1jenny','prat']
l.sort()
print(l)

['prat', 'reevan 1jenny', 'shoba1']


In [40]:
l.sort(reverse=True)
print(l)

['shoba1', 'reevan 1jenny', 'prat']


In [41]:
x=[10,20,30,40]
y=x[:]
y[1]=777
print(x)
print(y)

[10, 20, 30, 40]
[10, 777, 30, 40]


In [43]:
x=[10,20,30,40]
y=x.copy()
y[1]=777
print(x)
print(y)

[10, 20, 30, 40]
[10, 777, 30, 40]


In [45]:
a=[10,20,30]
b=[40,50,60]
c=a+b
print(c)

x=[10,20,30]
y=x*3
print(y)


[10, 20, 30, 40, 50, 60]
[10, 20, 30, 10, 20, 30, 10, 20, 30]


In [46]:
X=['MITE','MANGALORE','NITTE']
Y=['MITE','MANGALORE','NITTE']
X==Y
X!=Y
Z=['MITE','MANGALORE','NITTE']
X==Z

True

In [47]:
m=[10,20,30,40,[50,60,70]]
m[3]
m[4][1]
m.clear()
n=[1,2,3,4]
print(4 in n)

True


In [48]:
s=[2**x for x in range(1,6)]
print (s)

[2, 4, 8, 16, 32]


In [49]:
words=['mite','mysore','anubhav']
l=[w[0] for w in words]
print(1)

1


In [53]:
def times2(var):
    return var*2
#lambda var:var*2
seq =[1,2,3,4,5]
list(map(times2,seq))

[2, 4, 6, 8, 10]

In [54]:

seq =[1,2,3,4,5]
lambda var:var*2
list(map(lambda var:var*2,seq))

[2, 4, 6, 8, 10]

In [55]:

seq =[1,2,3,4,5]
lambda var:var*2
list(map(lambda var:var*2,seq))
list(filter(lambda item:item%2==0,seq))

[2, 4]

In [1]:
import numpy as np
my_list=[1,2,3]
my_list
np.array(my_list)

array([1, 2, 3])

In [2]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]
my_matrix
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [6]:
np.zeros(3)

array([0., 0., 0.])

In [7]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [11]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
np.random.rand(2)

array([0.86056326, 0.09142288])

In [13]:
np.random.rand(5,5)

array([[0.70758448, 0.06508515, 0.98935057, 0.25009573, 0.3394668 ],
       [0.5093068 , 0.36328313, 0.94793865, 0.45771805, 0.74289474],
       [0.71144077, 0.53649319, 0.48458971, 0.24438667, 0.58433318],
       [0.4847905 , 0.61931868, 0.78298071, 0.38409367, 0.45202751],
       [0.81830881, 0.22610037, 0.21434392, 0.55041826, 0.30549299]])

In [14]:
np.random.randn(5,5)

array([[-1.26080579, -0.78684628, -1.12268532,  0.22104077,  1.31501632],
       [ 0.91760304, -0.79359436, -0.65458485,  1.36892439,  0.56936391],
       [-1.366144  ,  2.28685935, -1.07833243,  0.12454743, -2.0457706 ],
       [ 1.04531392, -0.0094469 , -1.7734398 ,  0.09658423, -0.68627788],
       [ 0.15539988,  0.3386532 ,  0.34271213, -0.02042597,  0.88706754]])

In [15]:
np.random.randint(1,100,10)

array([24, 65, 24, 14, 41, 69, 17, 56, 41, 82])

In [17]:
arr=np.arange(25)

In [19]:
runarr=np.random.randint(0,50,10)

In [20]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [23]:
arr.reshape(5,5)



array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
runarr.max()


47

In [25]:
runarr.argmax()


6

In [26]:
argmin and min

NameError: name 'argmin' is not defined

In [27]:
arr.shape

(25,)

In [28]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [30]:
arr.reshape(1,25).shape

(1, 25)

In [31]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [32]:
arr.reshape(25,1).shape

(25, 1)

In [33]:
arr.dtype

dtype('int32')

In [34]:
arr=np.arange(0,10)

In [35]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [36]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [37]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [38]:
arr/arr

C:\Users\hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [39]:
1/arr

C:\Users\hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [40]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [41]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [42]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [43]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [44]:
np.log(arr)

C:\Users\hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [45]:
arr=np.arange(0,11)

In [46]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
arr[8]

8

In [48]:
arr[1:5]

array([1, 2, 3, 4])

In [49]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [50]:
arr[0:5]=100

In [51]:
arr=np.arange(0,11)

In [52]:
arr>4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [53]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [54]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [55]:
np.ones(15)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [61]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [62]:
np.arange(10,80,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78])

In [ ]:
ab=np.arange(0,9)